apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yy7b6mkvo-java-quarkus
  janus-idp.io/tekton: yy7b6mkvo-java-quarkus
  backstage.io/kubernetes-id: yy7b6mkvo-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: yy7b6mkvo-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
